version: '3.8'
services:
  envoy:
    container_name: envoy
    build:
      context: ./
    volumes:
#      - ./envoy-l4.yaml:/etc/envoy/envoy.yaml:ro
      - ./envoy-l7.yaml:/etc/envoy/envoy.yaml:ro
      - ./packets:/app/packets
    networks:
      - client
      - origin
networks:
  client:
    external: true
  origin:
    external: true

