version: '3.8'
services:
  client:
    container_name: client
    build:
      context: ./
    command: sleep infinity
    volumes:
      - ./packets:/app/packets
    networks:
      - client
networks:
  client:
    name: client

