version: '3.8'
services:
  client:
    container_name: client
    build:
      context: ../client
    command: sleep infinity
    volumes:
      - ../client/packets:/app/packets
    networks:
      - client
  proxy:
    container_name: proxy
    build:
      context: ./
    volumes:
      - ./squid.conf:/etc/squid/squid.conf:ro
      - ./packets:/app/packets
    networks:
      - client
      - origin
  origin:
    container_name: origin
    image: nginx:1.25.1
    networks:
      - origin
networks:
  client:
  origin:

