version: '3.8'
services:
  haproxy:
    container_name: haproxy
    build:
      context: ./
    volumes:
      - ./haproxy.cfg:/etc/haproxy/haproxy.cfg:ro
      - ./packets:/app/packets
    networks:
      - client
      - origin
networks:
  client:
    external: true
  origin:
    external: true

